// <auto-generated />
namespace AutoLotDAL_4._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class TimeStamps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TimeStamps));
        
        string IMigrationMetadata.Id
        {
            get { return "201911270809189_TimeStamps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
